version: '3'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db:3306 -schemas=make_magic -user=root -password= -connectRetries=60 -locations=filesystem:/flyway/sql/target/classes/db/migration/ migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=make_magic
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
    links:
      - make_magic
  make_magic:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: make_magic/api
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005, -DpreferIPv4Stack=true
      - PROFILE=prod